### PR TITLE
Remove columns with empty headers

### PR DESCRIPTION
**Pull request by warwickmm**
These columns were either empty, or simply contained unnecessary row numbers.

### CODE REVIEW

**Comment by warwickmm** [comment]
Sorry @dwillis, I noticed that this removed a column from some "tickets" files.  My code had assumed that these were simply unnecessary row numbers, but I'm not sure that's the case (the column header is empty so the purpose is unclear).  Should I revert some of these changes?

**Comment by warwickmm** [comment]
I believe the row numbers are added because `to_csv` is called without `index=False`

https://github.com/openelections/openelections-data-sd/blob/e0b7b0b925aec168c83966f9e3576ed92147cef2/scripts/tickets.py#L279-L285

In my opinion, the row numbers aren't that helpful and make the file more difficult to maintain.  Are these necessary?

/cc @martin-allen

**Comment by dwillis** [comment]
@warwickmm @martin-allen I don't think they are?

**Comment by warwickmm** [comment]
That's my feeling as well.  Unless @martin-allen says otherwise, I'll leave these changes as-is.  However, I would recommend that we modify `tickets.py` so that the row numbers (index) are not written.

**Pull request merged**
